In [7]:
import pandas as pd

df = pd.read_csv("employees.csv")
df.isnull().sum()

emp_id               0
name                 0
age                 15
gender               0
department           8
designation          0
salary              21
city                10
join_date            0
experience_years     0
rating              25
email                0
dtype: int64

Handling Missing Values: dropna()

In [8]:
# df_clean = df.dropna()
df_clean = df.dropna(subset=["salary","department"])
# df.dropna(how="all") # Very rare, all columns are Missing
df_clean

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-17,34,4.3,bhavna.saxena@company.com
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.0,Mumbai,11-03-15,30,NaN,rohan.shah@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
5,1006,Rahul Gupta,51.0,Male,Product,VP,209477.0,Ahmedabad,26-09-19,29,3.2,rahul.gupta@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-19,13,3.5,pallavi.chauhan@company.com
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.0,Mumbai,05-11-23,19,4.4,shweta.pillai@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-19,16,3.0,rakesh.chopra@company.com

Handling Missing Values: fillna()

In [ ]:
df["rating"]= df["rating"].fillna(0)
df["salary"] =df["salary"].fillna(df["salary"].mean())
df["age"] =df["age"].fillna(df["age"].median())
df["department"] =df["department"].fillna(df["department"].mode()[0])
df

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.000000,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,85756.235537,Pune,24-05-16,15,0.0,aadhya.nair@company.com
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.000000,Pune,28-06-17,34,4.3,bhavna.saxena@company.com
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.000000,Mumbai,11-03-15,30,0.0,rohan.shah@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.000000,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.000000,kolkata,09-10-19,13,3.5,pallavi.chauhan@company.com
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113.000000,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.000000,Chennai,16-03-18,5,3.3,aditya.mishra@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.000000,Mumbai,05-11-23,19,4.4,shweta.pillai@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.000000,Surat,20-08-19,16,3.0,rakesh.chopra@company.com

In [18]:
# Q1: Find the percentage of missing values in the 'rating' column.
df = pd.read_csv("employees.csv")
print(f"Percentage = {df["rating"].isnull().sum() / len(df) * 100:.2f}")

Percentage = 4.95

In [ ]:
# Fill missing 'age' values with the median age.
# df["age"] = df["age"].fillna(df["age"].median())

# Drop all rows where 'department' is missing
# df = df.dropna(subset=["department"])

# Fill missing 'city' values with 'Unknown'.
df["city"] = df["city"].fillna("Unknown")