In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv("employees.csv")
df['salary']=df['salary'].fillna(0).astype(int)

# Bins are (left, right]
# (0,40000] -> >0 and <=40000
bins=[0,40000, 70000, 100000,150000,300000]
labels=["Very Low","Low","Medium","High","Very High"]

# Bins are [left, right)
df['salary_range']=pd.cut(df['salary'],bins=bins,labels=labels)

df[['salary','salary_range']]

     salary salary_range
0     32153     Very Low
1         0          NaN
2     32123     Very Low
3     72798       Medium
4     91113       Medium
..      ...          ...
510   21314     Very Low
511   52374          Low
512   80129       Medium
513   48893          Low
514   74288       Medium

[515 rows x 2 columns]

In [11]:
# Using qcut
"""
0 43243, 313213,3231

low -> 0
-80000
-160000
- 240000
highest -> 456333

Q1,Q2,Q3,Q4
"""
df['salary_quartile']=pd.qcut(df['salary'],q=4,labels=["Q1","Q2","Q3","Q4"])
df['salary_tercile']=pd.qcut(df['salary'],q=3,labels=["Low","Medium","High"])
df[["salary","salary_quartile","salary_tercile"]]

     salary salary_quartile salary_tercile
0     32153              Q1            Low
1         0              Q1            Low
2     32123              Q1            Low
3     72798              Q2         Medium
4     91113              Q3         Medium
..      ...             ...            ...
510   21314              Q1            Low
511   52374              Q2            Low
512   80129              Q3         Medium
513   48893              Q1            Low
514   74288              Q2         Medium

[515 rows x 3 columns]